In [1]:
import pandas as pd
import glob
import os
import re

In [2]:
liste_fede_olympique = [
                    "athlétisme",
                    "aviron",
                    "badminton",
                    "baseball", 
                    "softball",
                    "basketball",
                    "boxe",
                    "canoë-kayak et sports de pagaie",
                    "cyclisme",
                    "équitation",
                    "escrime",
                    "football",
                    "football américain",
                    "sports de glace",
                    "golf",
                    "gymnastique",
                    "haltérophilie, musculation",
                    "handball",
                    "hockey",
                    "hockey sur glace",
                    "judo, jujitsu",
                    "lutte",
                    "montagne et de l'escalade",
                    "natation",
                    "pentathlon moderne",
                    "roller et skateboard",
                    "rugby",
                    "ski",
                    "squash",
                    "surf",
                    "taekwondo",
                    "tennis",
                    "tennis de table",
                    "tir",
                    "tir à l'arc",
                    "triathlon",
                    "voile",
                    "volley"
                    ]

In [3]:
len(liste_fede_olympique)

38

# Exploration du fichier de 2023

In [ ]:
# Fichier source disponible : https://injep.fr/donnee/recensement-des-licences-et-clubs-sportifs-2023/

In [4]:
lien = r"C:\Users\glese\Mon Drive\Wild\projet_3_devenir_champion\database\licences\Lics_2023_semidef.csv"
df = pd.read_csv(lien, sep=';', usecols=["Code 2023", "Fédération", "Année", "Sexe", "TrancheAge", "GrandeTrancheAge", "Région", "Département", "Licences annuelles"])

## Filtre sur les sports olympiques

In [5]:
df["Olympique"] = df["Fédération"].apply(lambda x: "Yes" if any(sport in x.lower() for sport in liste_fede_olympique) else "No")
display(df)

,Code 2023,Fédération,Année,Sexe,TrancheAge,GrandeTrancheAge,Région,Département,Licences annuelles,Olympique
0,101,Fédération Française d'Athlétisme,2023,F,a - de 1 à 4 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,2,Yes
1,101,Fédération Française d'Athlétisme,2023,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,10,Yes
2,101,Fédération Française d'Athlétisme,2023,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,24,Yes
3,101,Fédération Française d'Athlétisme,2023,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,29,Yes
4,101,Fédération Française d'Athlétisme,2023,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,63,Yes
...,...,...,...,...,...,...,...,...,...,...
844570,605,Union Sportive de l'Enseignement du Premier Degré,2023,H,k - de 50 à 54 ans,3 - Adultes (21-55),COM - COM,988 - Nouvelle-Calédonie,1,No
844571,605,Union Sportive de l'Enseignement du Premier Degré,2023,H,l - de 55 à 59 ans,3 - Adultes (21-55),COM - COM,988 - Nouvelle-Calédonie,3,No
844572,605,Union Sportive de l'Enseignement du Premier Degré,2023,H,l - de 55 à 59 ans,4 - Seniors (56-99),COM - COM,988 - Nouvelle-Calédonie,2,No
844573,605,Union Sportive de l'Enseignement du Premier Degré,2023,H,m - de 60 à 64 ans,4 - Seniors (56-99),COM - COM,988 - Nouvelle-Calédonie,1,No
844574,605,Union Sportive de l'Enseignement du Premier Degré,2023,H,m - de 60 à 64 ans,4 - Seniors (56-99),COM - COM,988 - Nouvelle-Calédonie,2,No

In [6]:
df_olympique = df[df["Olympique"] == "Yes"]

df_olympique_2 = df_olympique[~df_olympique["Fédération"].isin([
    "Fédération Française d'Éducation Physique et de Gymnastique Volontaire", 
    "Fédération Française de Motocyclisme",
    "Fédération Française de Savate, Boxe Française et Disciplines Associées",
    "Fédération Française de Ski Nautique et de Wakeboard",
    "Fédération Française de Rugby à XIII",
    "Fédération Française de Char à Voile",
    "Fédération Française des Sports de Traîneau, de Ski VTT Joëring et de Canicross",
    "Fédération Française de Javelot Tir sur Cible",
    "Fédération de Boxe Américaine et Disciplines Associées"
    ])]

display(df_olympique_2.value_counts("Fédération"))

Fédération
Fédération Française de Tennis                                           17590
Fédération Française de Golf                                             16865
Fédération Française d'Équitation                                        15930
Fédération Française d'Athlétisme                                        15760
Fédération Française de Football                                         15701
Fédération Française de Natation                                         15690
Fédération Française de Judo, Jujitsu, Kendo et Disciplines Associées    15589
Fédération Française de Tir                                              15056
Fédération Française de Basketball                                       14538
Fédération Française de Handball                                         13796
Fédération Française de Tennis de Table                                  13701
Fédération Française de Voile                                            13609
Fédération Française de Rugby                                            13349
Fédération Française de Cyclisme                                         12849
Fédération Française de Badminton                                        12716
Fédération Française de Tir à l'Arc                                      12668
Fédération Française de Gymnastique                                      12489
Fédération Française de la Montagne et de l'Escalade                     11229
Fédération Française de Volley                                           10903
Fédération Française de Triathlon et Disciplines Enchainées              10772
Fédération Française de Canoë-Kayak et Sports de Pagaie                   9860
Fédération Française de Boxe                                              9793
Fédération Française d'Escrime                                            9292
Fédération Française de Roller et Skateboard                              9180
Fédération Française d'Aviron                                             9140
Fédération Française de Ski                                               8253
Fédération Française de Taekwondo et Disciplines Associées                7476
Fédération Française d'Haltérophilie, Musculation                         6874
Fédération Française de Squash                                            5492
Fédération Française de Lutte                                             5356
Fédération Française de Hockey sur Glace                                  5265
Fédération Française des Sports de Glace                                  4805
Fédération Française de Baseball, Softball                                4483
Fédération Française de Football Américain                                4240
Fédération Française de Surf                                              3345
Fédération Française de Hockey                                            2641
Fédération Française de Pentathlon Moderne                                1078
Name: count, dtype: int64

In [7]:
df_olympique_3 = df_olympique_2[~df_olympique_2['Région'].isin(["NR - Non réparti", "ETR - Etranger"])]
display(df_olympique_3)

,Code 2023,Fédération,Année,Sexe,TrancheAge,GrandeTrancheAge,Région,Département,Licences annuelles,Olympique
0,101,Fédération Française d'Athlétisme,2023,F,a - de 1 à 4 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,2,Yes
1,101,Fédération Française d'Athlétisme,2023,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,10,Yes
2,101,Fédération Française d'Athlétisme,2023,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,24,Yes
3,101,Fédération Française d'Athlétisme,2023,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,29,Yes
4,101,Fédération Française d'Athlétisme,2023,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,63,Yes
...,...,...,...,...,...,...,...,...,...,...
398554,141,Fédération Française de Squash,2023,H,m - de 60 à 64 ans,4 - Seniors (56-99),COM - COM,988 - Nouvelle-Calédonie,5,Yes
398555,141,Fédération Française de Squash,2023,H,m - de 60 à 64 ans,4 - Seniors (56-99),COM - COM,988 - Nouvelle-Calédonie,2,Yes
398556,141,Fédération Française de Squash,2023,H,m - de 60 à 64 ans,4 - Seniors (56-99),COM - COM,988 - Nouvelle-Calédonie,2,Yes
398557,141,Fédération Française de Squash,2023,H,n - de 65 à 69 ans,4 - Seniors (56-99),COM - COM,988 - Nouvelle-Calédonie,2,Yes
398558,141,Fédération Française de Squash,2023,H,o - de 70 à 74 ans,4 - Seniors (56-99),COM - COM,988 - Nouvelle-Calédonie,1,Yes

In [8]:
df_olympique_3.loc[:,"Département"] = df_olympique_3.loc[:,"Département"].apply(lambda x: re.sub(r" - ", ", ", x))
df_olympique_3.loc[:,"geoloc_dep"] = df_olympique_3.loc[:,"Département"] + ", France"
df_olympique_3 = df_olympique_3.rename(columns={"Code 2023" : "id_federation"})
df_olympique_3 = df_olympique_3.drop(columns=["Olympique", "GrandeTrancheAge", "Année"])
display(df_olympique_3)

C:\Users\glese\AppData\Local\Temp\ipykernel_18716\1962664457.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_olympique_3.loc[:,"geoloc_dep"] = df_olympique_3.loc[:,"Département"] + ", France"

,id_federation,Fédération,Sexe,TrancheAge,Région,Département,Licences annuelles,geoloc_dep
0,101,Fédération Française d'Athlétisme,F,a - de 1 à 4 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",2,"01, Ain, France"
1,101,Fédération Française d'Athlétisme,F,b - de 5 à 9 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",10,"01, Ain, France"
2,101,Fédération Française d'Athlétisme,F,b - de 5 à 9 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",24,"01, Ain, France"
3,101,Fédération Française d'Athlétisme,F,b - de 5 à 9 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",29,"01, Ain, France"
4,101,Fédération Française d'Athlétisme,F,b - de 5 à 9 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",63,"01, Ain, France"
...,...,...,...,...,...,...,...,...
398554,141,Fédération Française de Squash,H,m - de 60 à 64 ans,COM - COM,"988, Nouvelle-Calédonie",5,"988, Nouvelle-Calédonie, France"
398555,141,Fédération Française de Squash,H,m - de 60 à 64 ans,COM - COM,"988, Nouvelle-Calédonie",2,"988, Nouvelle-Calédonie, France"
398556,141,Fédération Française de Squash,H,m - de 60 à 64 ans,COM - COM,"988, Nouvelle-Calédonie",2,"988, Nouvelle-Calédonie, France"
398557,141,Fédération Française de Squash,H,n - de 65 à 69 ans,COM - COM,"988, Nouvelle-Calédonie",2,"988, Nouvelle-Calédonie, France"
398558,141,Fédération Française de Squash,H,o - de 70 à 74 ans,COM - COM,"988, Nouvelle-Calédonie",1,"988, Nouvelle-Calédonie, France"

## Création table tranche d'age

In [24]:
df_olympique_3["id_tranche_age"] = df_olympique_3["TrancheAge"].apply(lambda x: re.findall(r"^\w{1}", x)[0])
display(df_olympique_3)

,id_federation,Fédération,Sexe,TrancheAge,Région,Département,Licences annuelles,geoloc_dep,id_tranche_age
0,101,Fédération Française d'Athlétisme,F,a - de 1 à 4 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",2,"01, Ain, France",a
1,101,Fédération Française d'Athlétisme,F,b - de 5 à 9 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",10,"01, Ain, France",b
2,101,Fédération Française d'Athlétisme,F,b - de 5 à 9 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",24,"01, Ain, France",b
3,101,Fédération Française d'Athlétisme,F,b - de 5 à 9 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",29,"01, Ain, France",b
4,101,Fédération Française d'Athlétisme,F,b - de 5 à 9 ans,84 - Auvergne-Rhône-Alpes,"01, Ain",63,"01, Ain, France",b
...,...,...,...,...,...,...,...,...,...
398554,141,Fédération Française de Squash,H,m - de 60 à 64 ans,COM - COM,"988, Nouvelle-Calédonie",5,"988, Nouvelle-Calédonie, France",m
398555,141,Fédération Française de Squash,H,m - de 60 à 64 ans,COM - COM,"988, Nouvelle-Calédonie",2,"988, Nouvelle-Calédonie, France",m
398556,141,Fédération Française de Squash,H,m - de 60 à 64 ans,COM - COM,"988, Nouvelle-Calédonie",2,"988, Nouvelle-Calédonie, France",m
398557,141,Fédération Française de Squash,H,n - de 65 à 69 ans,COM - COM,"988, Nouvelle-Calédonie",2,"988, Nouvelle-Calédonie, France",n
398558,141,Fédération Française de Squash,H,o - de 70 à 74 ans,COM - COM,"988, Nouvelle-Calédonie",1,"988, Nouvelle-Calédonie, France",o

In [29]:
df_tranche_age = df_olympique_3.groupby("id_tranche_age")["TrancheAge"].unique().reset_index()
df_tranche_age["TrancheAge"] = df_tranche_age["TrancheAge"].apply(lambda x: re.findall(r"\d+\s+à\s+\d+\s+ans", x[0])[0])
display(df_tranche_age)

   id_tranche_age   TrancheAge
0               a    1 à 4 ans
1               b    5 à 9 ans
2               c  10 à 14 ans
3               d  15 à 19 ans
4               e  20 à 24 ans
5               f  25 à 29 ans
6               g  30 à 34 ans
7               h  35 à 39 ans
8               i  40 à 44 ans
9               j  45 à 49 ans
10              k  50 à 54 ans
11              l  55 à 59 ans
12              m  60 à 64 ans
13              n  65 à 69 ans
14              o  70 à 74 ans
15              p  75 à 79 ans
16              q  80 à 99 ans

In [30]:
df_tranche_age.to_csv("table_id_tranche_age.csv")

## Création table Nom Fédération

In [9]:
df_fede = df_olympique_3.groupby("id_federation")["Fédération"].unique().reset_index()
df_fede["Fédération"] = df_fede["Fédération"].apply(lambda x: x[0])
df_fede = df_fede.rename(columns={"Fédération" : "nom_federation"})
display(df_fede)

    id_federation                                     nom_federation
0             101                  Fédération Française d'Athlétisme
1             102                      Fédération Française d'Aviron
2             103                  Fédération Française de Badminton
3             105                 Fédération Française de Basketball
4             106                       Fédération Française de Boxe
5             107  Fédération Française de Canoë-Kayak et Sports ...
6             108                   Fédération Française de Cyclisme
7             109                  Fédération Française d'Équitation
8             110                     Fédération Française d'Escrime
9             111                   Fédération Française de Football
10            112           Fédération Française des Sports de Glace
11            113                Fédération Française de Gymnastique
12            114  Fédération Française d'Haltérophilie, Musculation
13            115                   Fédération Française de Handball
14            116                     Fédération Française de Hockey
15            117  Fédération Française de Judo, Jujitsu, Kendo e...
16            118                      Fédération Française de Lutte
17            119                   Fédération Française de Natation
18            120         Fédération Française de Pentathlon Moderne
19            121                        Fédération Française de Ski
20            122  Fédération Française de Taekwondo et Disciplin...
21            123                     Fédération Française de Tennis
22            124            Fédération Française de Tennis de Table
23            125                        Fédération Française de Tir
24            126                Fédération Française de Tir à l'Arc
25            127  Fédération Française de Triathlon et Disciplin...
26            128                      Fédération Française de Voile
27            129                     Fédération Française de Volley
28            131           Fédération Française de Hockey sur Glace
29            132                       Fédération Française de Golf
30            133                      Fédération Française de Rugby
31            135  Fédération Française de la Montagne et de l'Es...
32            136       Fédération Française de Roller et Skateboard
33            137                       Fédération Française de Surf
34            138         Fédération Française de Baseball, Softball
35            140         Fédération Française de Football Américain
36            141                     Fédération Française de Squash

In [10]:
df_fede.to_csv("table_id_fede.csv")

## Export Table nombre de licences

In [38]:
df_olympique_4 = df_olympique_3.drop(columns=["Fédération", "TrancheAge", "Département"])
df_olympique_5 = df_olympique_4[["id_federation", "Sexe", "id_tranche_age", "Région", "geoloc_dep", "Licences annuelles"]]
display(df_olympique_5)

,id_federation,Sexe,id_tranche_age,Région,geoloc_dep,Licences annuelles
0,101,F,a,84 - Auvergne-Rhône-Alpes,"01, Ain, France",2
1,101,F,b,84 - Auvergne-Rhône-Alpes,"01, Ain, France",10
2,101,F,b,84 - Auvergne-Rhône-Alpes,"01, Ain, France",24
3,101,F,b,84 - Auvergne-Rhône-Alpes,"01, Ain, France",29
4,101,F,b,84 - Auvergne-Rhône-Alpes,"01, Ain, France",63
...,...,...,...,...,...,...
398554,141,H,m,COM - COM,"988, Nouvelle-Calédonie, France",5
398555,141,H,m,COM - COM,"988, Nouvelle-Calédonie, France",2
398556,141,H,m,COM - COM,"988, Nouvelle-Calédonie, France",2
398557,141,H,n,COM - COM,"988, Nouvelle-Calédonie, France",2
398558,141,H,o,COM - COM,"988, Nouvelle-Calédonie, France",1

In [39]:
df_olympique_4.to_csv("licence_2023_cleaned.csv")

# Création des fonctions pour analyses de tous les fichiers

In [12]:
def traitement_fichier_licences(lien):

    # Je lis le CSV en sélectionnant seulement les colonnes pertinentes
    df = pd.read_csv(lien, sep=';', usecols=["Fédération", "Année", "Sexe", "TrancheAge", "GrandeTrancheAge", "Région", "Département", "Licences annuelles"])

    # Je filtre les sports olympiques grâce à la liste fournie par le gouvernement
    df["Olympique"] = df["Fédération"].apply(lambda x: "Yes" if any(sport in x.lower() for sport in liste_fede_olympique) else "No")
    df_olympique = df[df["Olympique"] == "Yes"]

    # Je supprime les Fédé non filtrées comme prévues
    df_olympique_2 = df_olympique[~df_olympique["Fédération"].isin([
        "Fédération Française d'Éducation Physique et de Gymnastique Volontaire", 
        "Fédération Française de Motocyclisme",
        "Fédération Française de Savate, Boxe Française et Disciplines Associées",
        "Fédération Française de Ski Nautique et de Wakeboard",
        "Fédération Française de Rugby à XIII",
        "Fédération Française de Char à Voile",
        "Fédération Française des Sports de Traîneau, de Ski VTT Joëring et de Canicross",
        "Fédération Française de Javelot Tir sur Cible"
    ])]

    # Je supprime les régions "Non réparti" & "Etranger"
    df_olympique_3 = df_olympique_2[~df_olympique_2['Région'].isin(["NR - Non réparti", "ETR - Etranger"])]

    return df_olympique_3

In [13]:
def traiter_tous_fichiers_combine(dossier=".", pattern="*.csv"):
    """
    Traite tous les fichiers CSV d'un dossier et combine les résultats en un seul DataFrame
    """
    fichiers = glob.glob(os.path.join(dossier, pattern))
    
    resultats_combines = []
    
    for fichier in fichiers:
        print(f"Traitement de : {os.path.basename(fichier)}")
        try:
            df_traite = traitement_fichier_licences(fichier)
            resultats_combines.append(df_traite)
        except Exception as e:
            print(f"Erreur avec {fichier}: {e}")
    
    df_final = pd.concat(resultats_combines, ignore_index=True)
    print(f"Résultat final : {len(df_final)} lignes")

    df_final.to_csv("licences_2016-2023.csv", sep=';', index=False)
    print(f"Export réalisé")
    
    return df_final

In [14]:
df_final = traiter_tous_fichiers_combine(dossier="DataSource\Licences-annuelles-par-millesime-2016-2023", pattern="*.csv")

ValueError: No objects to concatenate

In [ ]:
display(df_final)
df_final.to_csv("licences_2016-2023.csv")

,Fédération,Année,Sexe,TrancheAge,GrandeTrancheAge,Région,Département,Licences annuelles,Olympique
0,Fédération Française d'Athlétisme,2016,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,1,Yes
1,Fédération Française d'Athlétisme,2016,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,13,Yes
2,Fédération Française d'Athlétisme,2016,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,28,Yes
3,Fédération Française d'Athlétisme,2016,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,49,Yes
4,Fédération Française d'Athlétisme,2016,F,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,76,Yes
...,...,...,...,...,...,...,...,...,...
3002748,Fédération de Boxe Américaine et Disciplines A...,2023,H,l - de 55 à 59 ans,4 - Seniors (56-99),11 - Île-de-France,92 - Hauts-de-Seine,1,Yes
3002749,Fédération de Boxe Américaine et Disciplines A...,2023,H,l - de 55 à 59 ans,4 - Seniors (56-99),11 - Île-de-France,92 - Hauts-de-Seine,1,Yes
3002750,Fédération de Boxe Américaine et Disciplines A...,2023,H,m - de 60 à 64 ans,4 - Seniors (56-99),11 - Île-de-France,92 - Hauts-de-Seine,1,Yes
3002751,Fédération de Boxe Américaine et Disciplines A...,2023,H,n - de 65 à 69 ans,4 - Seniors (56-99),11 - Île-de-France,92 - Hauts-de-Seine,1,Yes
3002752,Fédération de Boxe Américaine et Disciplines A...,2023,H,i - de 40 à 44 ans,3 - Adultes (21-55),11 - Île-de-France,93 - Seine-Saint-Denis,1,Yes